#!/usr/bin/env python

def problem_12():
    """
    What is the value of the first triangle number to have over five
    hundred divisors?  The sequence of triangle numbers is generated by
    adding the natural numbers. So the 7th triangle number would be 1 +
    2 + 3 + 4 + 5 + 6 + 7 = 28.
    """
    pass

if __name__ == '__main__':
    print problem_12()
